### PR TITLE
fix deprecaitons related with gridsearch

### PR DESCRIPTION
**Pull request by kdw503**
This will work after merging the latest RegisterDeformation pull request and updating related tree-sha in HolyLabRegistry.

### CODE REVIEW

**Comment by timholy** [comment]
For the test failure, looks like you'll have to change https://github.com/HolyLab/RegisterDeformation.jl/blob/d50945368a13fda392a1061714ea1b1d085abdbc/test/runtests.jl#L289 to `".jld2"`.

**Comment by kdw503** [comment]
Thank you.

**Comment by kdw503** [comment]
Test failed because this package is a public package but some of its dependencies are not. Those are 'RegisterMismatch', 'RegisterCore', 'RegisterDeformation' and 'CenterindexedArrays'. And, if we make these packages as public then all their dependencies chain also should be public.
See https://github.com/HolyLab/HolyLabRegistry/issues/42.

**Comment by Cody-G** [comment]
Right, I think we were waiting on a chain of PRs to merge before making RegisterMismatch and others public (see https://github.com/HolyLab/RegisterMismatch.jl/issues/3).  But now it seems the time has come?  My understanding from Tim is that we should feel free to make the whole dependency tree for this package public.  If there are any outstanding PRs in the dependency tree then let's merge those first, then make them public.

**Comment by kdw503** [comment]
Related dependency chains are 
- CenterIndexedArrays
- CachedInterpolations
- RegisterUtilities
- RegisterCore : has one issue https://github.com/HolyLab/RegisterCore.jl/issues/1
- RegisterDeformation
- RegisterMismatchCommon
- RegisterMismatch

After fixing the issue and updating HolyLabRegistry, I will publish all the packages.

**Comment by timholy** [comment]
Yes, I'm fine with making these public.

**Comment by timholy** [comment]
We'll need better docs soon!

**Comment by kdw503** [comment]
QuadDIRECT also needs to be published.

**Comment by timholy** [comment]
I can register QuadDIRECT. Or should we add it to HolyLabRegistry?

**Comment by kdw503** [comment]
Yes, I think so. And also need to make the QuadDIRECT repo. as public.

**Comment by kdw503** [comment]
Oh, now I understand your question.
I think just adding to the HolyLabRegistry is enough to me.

**Comment by timholy** [comment]
QuadDIRECT is in my personal account and has always been public.

**Comment by kdw503** [comment]
Ok, I understand.
QuadDIRECT was added to HolyLabRegistry as using git protocol even though it is public.
That's why Travis test asks private key location for 'git@github.com'.
I will change the protocol to https in the HolyLabRegistry.

**Pull request merged**
