### PR TITLE
mxshift & initial_tfm elaboration

### PR DESCRIPTION
**Pull request by ianshmean**
Suggested modification to docstrings to help #22 

Please feel free to edit

### CODE REVIEW

**Comment by Cody-G** [comment]
Looks good to me, thanks!  I'll let Tim do the honors of merging.

**Comment by timholy** [comment]
This is great, many thanks!

**Comment by timholy** [comment]
On the topic of documentation, there's now some for https://github.com/HolyLab/RegisterCore.jl. You may or may not have been puzzled by `NumDenom`, but if so, now you can read more about it.

Part of the design of our registration stack is targeted at a deformable registration framework that is still private for now, so a few of the things those docs describes may seem a bit under-utilized. It *will* be public some day, when we can get around to documenting it and writing it up as a paper.

**Comment by ianshmean** [comment]
Great. The docs are helpful and I look forward to the paper! thanks, as ever

**Pull request merged**
